apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount | default ""}}
  selector:
    matchLabels:
      name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: docker-secret2
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            #override config.js file
            - name: config
              mountPath: "/usr/share/nginx/html/config.js"
              subPath: "config.js"
      terminationGracePeriodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}
            items:
                - key: "web.properties"
                  path: "config.js"       
