{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  tls:
    - hosts: [{{ .Values.ingress.host }}]
      secretName: {{ .Values.ingress.tls.secretName }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:  
          - path: {{ .Values.ingress.path }}{{.Values.ingress.pathSuffix}}
            backend:
              serviceName: {{ .Release.Name }}
              servicePort: http
          - path: {{ .Values.ingress.path }}/about
            backend:
              serviceName: {{ .Release.Name }}
              servicePort: http
          - path: {{ .Values.ingress.path }}/topics
            backend:
              serviceName: {{ .Release.Name }}
              servicePort: http
          - path: {{ .Values.ingress.path }}/settings
            backend:
              serviceName: {{ .Release.Name }}
              servicePort: http

{{- end -}}
